[package]
name = "rust-aisd"
version = "0.1.0"
authors = ["rogovskyyy <bart.rogovsky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.2.25"
rand = "0.8.3"
plotters = "0.3.0"